CREATE DATABASE PROYECTO2;

CREATE TABLE CLIENTS(
	CustomerID VARCHAR(15),
    AGE varchar(3),
    ChurnCategory VARCHAR(50),
    ChurnReason VARCHAR(50),
    City VARCHAR(50),
    Contract VARCHAR(50),
    Country VARCHAR(50),
    CustomerStatus VARCHAR(50),
    Gender VARCHAR(50),
    SatisfactionScore INT,
    State VARCHAR(50),
    TotalCharges INT,
    TotalRefunds INT
    );

ALTER TABLE CLIENTS MODIFY AGE INT;

-- IMPORT DATASET
LOAD DATA INFILE 'C:/Users/Tomy/Desktop/Proyectos Personales/Project 2 - Customer Churn Analysis (SQL)/data.csv'
INTO TABLE CLIENTS
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- EXPLORATION
desc clients;
select * from clients order by customerID;
SELECT CUSTOMERID, AGE, GENDER, COUNTRY, STATE, CUSTOMERSTATUS, CONTRACT, TOTALCHARGES, TOTALREFUNDS, SATISFACTIONSCORE FROM CLIENTS ORDER BY TOTALREFUNDS DESC;

-- NUMBER OF ACTIVE AND CHURNED // PERCENTAGE
SELECT CUSTOMERSTATUS, COUNT(*) AS AMOUNT, ROUND(COUNT(*)/(SELECT COUNT(*) FROM CLIENTS),2) AS PERCENTAGE 
FROM CLIENTS 
GROUP BY CUSTOMERSTATUS;

-- AVERAGE STAISFACTION BY STATUS
SELECT CUSTOMERSTATUS, ROUND(AVG(SATISFACTIONSCORE),2) AS AVGCHARGE 
FROM CLIENTS 
GROUP BY CUSTOMERSTATUS;

-- CHURNED SATISFACTION
SELECT 
    s.SATISFACTIONSCORE, 
    COUNT(c.CUSTOMERID) AS AMOUNT
FROM 
    (SELECT DISTINCT SATISFACTIONSCORE FROM CLIENTS) s
LEFT JOIN 
    CLIENTS c ON s.SATISFACTIONSCORE = c.SATISFACTIONSCORE AND c.CUSTOMERSTATUS = 'CHURNED'
GROUP BY 
    s.SATISFACTIONSCORE
ORDER BY 
    s.SATISFACTIONSCORE;

-- CLIENTS AVERAGE AGE 
SELECT AVG(AGE) FROM CLIENTS;

SELECT AGE, COUNT(*) AS AMOUNT FROM CLIENTS GROUP BY AGE ORDER BY AMOUNT DESC;
SELECT AGE, COUNT(*) AS AMOUNT FROM CLIENTS WHERE CUSTOMERSTATUS = 'CHURNED' GROUP BY AGE ORDER BY AMOUNT DESC;

SELECT CUSTOMERSTATUS, AGE, COUNT(*) AS AMOUNT 
FROM CLIENTS 
GROUP BY CUSTOMERSTATUS, AGE
ORDER BY AGE;

-- CLIENTS AVERAGE AGE BY STATUS
SELECT CUSTOMERSTATUS, ROUND(AVG(AGE),0) AVGAGE FROM CLIENTS GROUP BY CUSTOMERSTATUS;

-- CHURNED BY GENDER
SELECT GENDER, CUSTOMERSTATUS, COUNT(*) AS AMOUNT 
FROM CLIENTS 
WHERE CUSTOMERSTATUS = 'CHURNED' 
GROUP BY GENDER;

-- CHURNED CLIENTS BY CONTRACT
SELECT CONTRACT, CUSTOMERSTATUS, COUNT(*) AS AMOUNT 
FROM CLIENTS
WHERE CUSTOMERSTATUS = 'CHURNED'
GROUP BY CONTRACT;

-- AMOUNT BY CONTRACT AND STATUS
SELECT CONTRACT, CUSTOMERSTATUS, COUNT(*) AS AMOUNT 
FROM CLIENTS
GROUP BY CONTRACT, CUSTOMERSTATUS
ORDER BY CONTRACT, CUSTOMERSTATUS;

-- REASON OF CHURNED
SELECT CHURNCATEGORY, COUNT(*) AS AMOUNT
FROM CLIENTS
WHERE CUSTOMERSTATUS = 'CHURNED'
GROUP BY CHURNCATEGORY;

-- AVG CHARGES BY CLIENT
SELECT CUSTOMERSTATUS, CONTRACT, ROUND(AVG(TOTALCHARGES),0)
FROM CLIENTS
GROUP BY CUSTOMERSTATUS, CONTRACT;


